apiVersion: v1
kind: Secret
metadata:
  name: studyhub-secrets
  namespace: studyhub-dev
type: Opaque
stringData:
  DB_PASSWORD: "password"
  KEYCLOAK_CLIENT_SECRET: "D0SoSZu2DzFCN2ci1sZBGSarjKz7Z7V6"
  GOOGLE_GENAI_API_KEY: "AIzaSyCYM42dx8TR_1Nook5G96Ra3P70xSs3ToQ"
  LIVEKIT_URL: "wss://studhub-dev-xpq8abrl.livekit.cloud"
  LIVEKIT_API_KEY: "APIdwJZWgvf39B8"
  LIVEKIT_API_SECRET: "JyjpEjJDr5qfJRXjHyuNAVzY8HcV7Sfg6B8M2QYM6AQ"
